spring:
    application:
        name: eurekaserver

    security:
        basic:
            enabled: true
        user:
            name: mscourse-eureka-user
            password: 46d4736f921245ab8ae64f96de59b84a

server:
    port: 8761

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false